// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'mumble/config.dart';
import 'mumble/hardware/audio.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiClientInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2139598591;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_rumble',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiClientRustAudioEngineDebugInjectPcm({
    required RustAudioEngine that,
    required List<double> samples,
  });

  Stream<Float32List> crateApiClientRustAudioEngineDebugStartRecording({
    required RustAudioEngine that,
  });

  Future<void> crateApiClientRustAudioEngineDisconnect({
    required RustAudioEngine that,
  });

  Stream<AudioEvent> crateApiClientRustAudioEngineGetEventStream({
    required RustAudioEngine that,
  });

  Future<void> crateApiClientRustAudioEngineInitializeAudio({
    required RustAudioEngine that,
    required String host,
    required int port,
    required List<int> key,
    required List<int> encryptNonce,
    required List<int> decryptNonce,
  });

  RustAudioEngine crateApiClientRustAudioEngineNew();

  Future<void> crateApiClientRustAudioEngineSetAutomaticGainControl({
    required RustAudioEngine that,
    required bool enabled,
  });

  Future<void> crateApiClientRustAudioEngineSetConfig({
    required RustAudioEngine that,
    required MumbleConfig config,
  });

  Future<void> crateApiClientRustAudioEngineSetEchoCancellation({
    required RustAudioEngine that,
    required bool enabled,
  });

  Future<void> crateApiClientRustAudioEngineSetInputGain({
    required RustAudioEngine that,
    required double gain,
  });

  Future<void> crateApiClientRustAudioEngineSetNoiseSuppression({
    required RustAudioEngine that,
    required bool enabled,
  });

  Future<void> crateApiClientRustAudioEngineSetOutputVolume({
    required RustAudioEngine that,
    required double volume,
  });

  Future<void> crateApiClientRustAudioEngineSetPtt({
    required RustAudioEngine that,
    required bool active,
  });

  Future<void> crateApiClientRustAudioEngineSetUserVolume({
    required RustAudioEngine that,
    required int sessionId,
    required double volume,
  });

  Future<void> crateApiClientInitApp();

  Future<List<AudioDevice>> crateApiClientListAudioInputDevices();

  Future<List<AudioDevice>> crateApiClientListAudioOutputDevices();

  Future<MumbleChannel> crateApiClientMumbleChannelDefault();

  Future<MumbleUser> crateApiClientMumbleUserDefault();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RustAudioEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RustAudioEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RustAudioEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiClientRustAudioEngineDebugInjectPcm({
    required RustAudioEngine that,
    required List<double> samples,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(samples, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineDebugInjectPcmConstMeta,
        argValues: [that, samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineDebugInjectPcmConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_debug_inject_pcm",
        argNames: ["that", "samples"],
      );

  @override
  Stream<Float32List> crateApiClientRustAudioEngineDebugStartRecording({
    required RustAudioEngine that,
  }) {
    final sink = RustStreamSink<Float32List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
              that,
              serializer,
            );
            sse_encode_StreamSink_list_prim_f_32_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiClientRustAudioEngineDebugStartRecordingConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiClientRustAudioEngineDebugStartRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_debug_start_recording",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineDisconnect({
    required RustAudioEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineDisconnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_disconnect",
        argNames: ["that"],
      );

  @override
  Stream<AudioEvent> crateApiClientRustAudioEngineGetEventStream({
    required RustAudioEngine that,
  }) {
    final sink = RustStreamSink<AudioEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
              that,
              serializer,
            );
            sse_encode_StreamSink_audio_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiClientRustAudioEngineGetEventStreamConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineGetEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_get_event_stream",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineInitializeAudio({
    required RustAudioEngine that,
    required String host,
    required int port,
    required List<int> key,
    required List<int> encryptNonce,
    required List<int> decryptNonce,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(encryptNonce, serializer);
          sse_encode_list_prim_u_8_loose(decryptNonce, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientRustAudioEngineInitializeAudioConstMeta,
        argValues: [that, host, port, key, encryptNonce, decryptNonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineInitializeAudioConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_initialize_audio",
        argNames: [
          "that",
          "host",
          "port",
          "key",
          "encryptNonce",
          "decryptNonce",
        ],
      );

  @override
  RustAudioEngine crateApiClientRustAudioEngineNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineNewConstMeta =>
      const TaskConstMeta(debugName: "RustAudioEngine_new", argNames: []);

  @override
  Future<void> crateApiClientRustAudioEngineSetAutomaticGainControl({
    required RustAudioEngine that,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiClientRustAudioEngineSetAutomaticGainControlConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiClientRustAudioEngineSetAutomaticGainControlConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_automatic_gain_control",
        argNames: ["that", "enabled"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetConfig({
    required RustAudioEngine that,
    required MumbleConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_box_autoadd_mumble_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetConfigConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineSetConfigConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_config",
        argNames: ["that", "config"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetEchoCancellation({
    required RustAudioEngine that,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetEchoCancellationConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiClientRustAudioEngineSetEchoCancellationConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_echo_cancellation",
        argNames: ["that", "enabled"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetInputGain({
    required RustAudioEngine that,
    required double gain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_f_32(gain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetInputGainConstMeta,
        argValues: [that, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineSetInputGainConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_input_gain",
        argNames: ["that", "gain"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetNoiseSuppression({
    required RustAudioEngine that,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetNoiseSuppressionConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiClientRustAudioEngineSetNoiseSuppressionConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_noise_suppression",
        argNames: ["that", "enabled"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetOutputVolume({
    required RustAudioEngine that,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetOutputVolumeConstMeta,
        argValues: [that, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineSetOutputVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_output_volume",
        argNames: ["that", "volume"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetPtt({
    required RustAudioEngine that,
    required bool active,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_bool(active, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetPttConstMeta,
        argValues: [that, active],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineSetPttConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_ptt",
        argNames: ["that", "active"],
      );

  @override
  Future<void> crateApiClientRustAudioEngineSetUserVolume({
    required RustAudioEngine that,
    required int sessionId,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
            that,
            serializer,
          );
          sse_encode_u_32(sessionId, serializer);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientRustAudioEngineSetUserVolumeConstMeta,
        argValues: [that, sessionId, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientRustAudioEngineSetUserVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "RustAudioEngine_set_user_volume",
        argNames: ["that", "sessionId", "volume"],
      );

  @override
  Future<void> crateApiClientInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<AudioDevice>> crateApiClientListAudioInputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_device,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientListAudioInputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientListAudioInputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_audio_input_devices", argNames: []);

  @override
  Future<List<AudioDevice>> crateApiClientListAudioOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_device,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientListAudioOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientListAudioOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_audio_output_devices", argNames: []);

  @override
  Future<MumbleChannel> crateApiClientMumbleChannelDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mumble_channel,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientMumbleChannelDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientMumbleChannelDefaultConstMeta =>
      const TaskConstMeta(debugName: "mumble_channel_default", argNames: []);

  @override
  Future<MumbleUser> crateApiClientMumbleUserDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mumble_user,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientMumbleUserDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientMumbleUserDefaultConstMeta =>
      const TaskConstMeta(debugName: "mumble_user_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RustAudioEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RustAudioEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustAudioEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustAudioEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustAudioEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RustAudioEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<AudioEvent> dco_decode_StreamSink_audio_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioBufferSize dco_decode_audio_buffer_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AudioBufferSize_Default();
      case 1:
        return AudioBufferSize_Fixed(dco_decode_u_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AudioDevice(
      name: dco_decode_String(arr[0]),
      id: dco_decode_String(arr[1]),
    );
  }

  @protected
  AudioEvent dco_decode_audio_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AudioEvent_AudioVolume(dco_decode_f_32(raw[1]));
      case 1:
        return AudioEvent_UserTalking(
          dco_decode_u_32(raw[1]),
          dco_decode_bool(raw[2]),
        );
      case 2:
        return AudioEvent_Disconnected(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MumbleConfig dco_decode_box_autoadd_mumble_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mumble_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_device).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MumbleChannel dco_decode_mumble_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MumbleChannel(
      id: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      parentId: dco_decode_opt_box_autoadd_u_32(arr[2]),
      position: dco_decode_i_32(arr[3]),
      description: dco_decode_opt_String(arr[4]),
      isEnterRestricted: dco_decode_bool(arr[5]),
    );
  }

  @protected
  MumbleConfig dco_decode_mumble_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return MumbleConfig(
      transmissionMode: dco_decode_transmission_mode(arr[0]),
      vadThreshold: dco_decode_f_32(arr[1]),
      outgoingAudioBitrate: dco_decode_u_32(arr[2]),
      outgoingAudioMsPerPacket: dco_decode_u_32(arr[3]),
      incomingJitterBufferMs: dco_decode_u_32(arr[4]),
      playbackDeviceId: dco_decode_opt_String(arr[5]),
      playbackHwBufferSize: dco_decode_audio_buffer_size(arr[6]),
      captureHwBufferSize: dco_decode_audio_buffer_size(arr[7]),
      captureDeviceId: dco_decode_opt_String(arr[8]),
      echoCancellation: dco_decode_bool(arr[9]),
      noiseSuppression: dco_decode_bool(arr[10]),
      automaticGainControl: dco_decode_bool(arr[11]),
    );
  }

  @protected
  MumbleUser dco_decode_mumble_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MumbleUser(
      session: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      channelId: dco_decode_u_32(arr[2]),
      isTalking: dco_decode_bool(arr[3]),
      isMuted: dco_decode_bool(arr[4]),
      isDeafened: dco_decode_bool(arr[5]),
      isSuppressed: dco_decode_bool(arr[6]),
      isRegistered: dco_decode_bool(arr[7]),
      userId: dco_decode_opt_box_autoadd_u_32(arr[8]),
      comment: dco_decode_opt_String(arr[9]),
      avatar: dco_decode_opt_list_prim_u_8_strict(arr[10]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  TransmissionMode dco_decode_transmission_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransmissionMode.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustAudioEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustAudioEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustAudioEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RustAudioEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<AudioEvent> sse_decode_StreamSink_audio_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioBufferSize sse_decode_audio_buffer_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AudioBufferSize_Default();
      case 1:
        var var_field0 = sse_decode_u_32(deserializer);
        return AudioBufferSize_Fixed(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    return AudioDevice(name: var_name, id: var_id);
  }

  @protected
  AudioEvent sse_decode_audio_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_f_32(deserializer);
        return AudioEvent_AudioVolume(var_field0);
      case 1:
        var var_field0 = sse_decode_u_32(deserializer);
        var var_field1 = sse_decode_bool(deserializer);
        return AudioEvent_UserTalking(var_field0, var_field1);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return AudioEvent_Disconnected(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MumbleConfig sse_decode_box_autoadd_mumble_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mumble_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MumbleChannel sse_decode_mumble_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_parentId = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_position = sse_decode_i_32(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_isEnterRestricted = sse_decode_bool(deserializer);
    return MumbleChannel(
      id: var_id,
      name: var_name,
      parentId: var_parentId,
      position: var_position,
      description: var_description,
      isEnterRestricted: var_isEnterRestricted,
    );
  }

  @protected
  MumbleConfig sse_decode_mumble_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transmissionMode = sse_decode_transmission_mode(deserializer);
    var var_vadThreshold = sse_decode_f_32(deserializer);
    var var_outgoingAudioBitrate = sse_decode_u_32(deserializer);
    var var_outgoingAudioMsPerPacket = sse_decode_u_32(deserializer);
    var var_incomingJitterBufferMs = sse_decode_u_32(deserializer);
    var var_playbackDeviceId = sse_decode_opt_String(deserializer);
    var var_playbackHwBufferSize = sse_decode_audio_buffer_size(deserializer);
    var var_captureHwBufferSize = sse_decode_audio_buffer_size(deserializer);
    var var_captureDeviceId = sse_decode_opt_String(deserializer);
    var var_echoCancellation = sse_decode_bool(deserializer);
    var var_noiseSuppression = sse_decode_bool(deserializer);
    var var_automaticGainControl = sse_decode_bool(deserializer);
    return MumbleConfig(
      transmissionMode: var_transmissionMode,
      vadThreshold: var_vadThreshold,
      outgoingAudioBitrate: var_outgoingAudioBitrate,
      outgoingAudioMsPerPacket: var_outgoingAudioMsPerPacket,
      incomingJitterBufferMs: var_incomingJitterBufferMs,
      playbackDeviceId: var_playbackDeviceId,
      playbackHwBufferSize: var_playbackHwBufferSize,
      captureHwBufferSize: var_captureHwBufferSize,
      captureDeviceId: var_captureDeviceId,
      echoCancellation: var_echoCancellation,
      noiseSuppression: var_noiseSuppression,
      automaticGainControl: var_automaticGainControl,
    );
  }

  @protected
  MumbleUser sse_decode_mumble_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_session = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_channelId = sse_decode_u_32(deserializer);
    var var_isTalking = sse_decode_bool(deserializer);
    var var_isMuted = sse_decode_bool(deserializer);
    var var_isDeafened = sse_decode_bool(deserializer);
    var var_isSuppressed = sse_decode_bool(deserializer);
    var var_isRegistered = sse_decode_bool(deserializer);
    var var_userId = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    var var_avatar = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return MumbleUser(
      session: var_session,
      name: var_name,
      channelId: var_channelId,
      isTalking: var_isTalking,
      isMuted: var_isMuted,
      isDeafened: var_isDeafened,
      isSuppressed: var_isSuppressed,
      isRegistered: var_isRegistered,
      userId: var_userId,
      comment: var_comment,
      avatar: var_avatar,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TransmissionMode sse_decode_transmission_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransmissionMode.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    RustAudioEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    RustAudioEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRustAudioEngine(
    RustAudioEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RustAudioEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_audio_event_Sse(
    RustStreamSink<AudioEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_buffer_size(
    AudioBufferSize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AudioBufferSize_Default():
        sse_encode_i_32(0, serializer);
      case AudioBufferSize_Fixed(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(field0, serializer);
    }
  }

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.id, serializer);
  }

  @protected
  void sse_encode_audio_event(AudioEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AudioEvent_AudioVolume(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_f_32(field0, serializer);
      case AudioEvent_UserTalking(field0: final field0, field1: final field1):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(field0, serializer);
        sse_encode_bool(field1, serializer);
      case AudioEvent_Disconnected(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mumble_config(
    MumbleConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mumble_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mumble_channel(MumbleChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_32(self.parentId, serializer);
    sse_encode_i_32(self.position, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_bool(self.isEnterRestricted, serializer);
  }

  @protected
  void sse_encode_mumble_config(MumbleConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transmission_mode(self.transmissionMode, serializer);
    sse_encode_f_32(self.vadThreshold, serializer);
    sse_encode_u_32(self.outgoingAudioBitrate, serializer);
    sse_encode_u_32(self.outgoingAudioMsPerPacket, serializer);
    sse_encode_u_32(self.incomingJitterBufferMs, serializer);
    sse_encode_opt_String(self.playbackDeviceId, serializer);
    sse_encode_audio_buffer_size(self.playbackHwBufferSize, serializer);
    sse_encode_audio_buffer_size(self.captureHwBufferSize, serializer);
    sse_encode_opt_String(self.captureDeviceId, serializer);
    sse_encode_bool(self.echoCancellation, serializer);
    sse_encode_bool(self.noiseSuppression, serializer);
    sse_encode_bool(self.automaticGainControl, serializer);
  }

  @protected
  void sse_encode_mumble_user(MumbleUser self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.session, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.channelId, serializer);
    sse_encode_bool(self.isTalking, serializer);
    sse_encode_bool(self.isMuted, serializer);
    sse_encode_bool(self.isDeafened, serializer);
    sse_encode_bool(self.isSuppressed, serializer);
    sse_encode_bool(self.isRegistered, serializer);
    sse_encode_opt_box_autoadd_u_32(self.userId, serializer);
    sse_encode_opt_String(self.comment, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.avatar, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_transmission_mode(
    TransmissionMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class RustAudioEngineImpl extends RustOpaque implements RustAudioEngine {
  // Not to be used by end users
  RustAudioEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RustAudioEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RustAudioEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RustAudioEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RustAudioEnginePtr,
  );

  Future<void> debugInjectPcm({required List<double> samples}) =>
      RustLib.instance.api.crateApiClientRustAudioEngineDebugInjectPcm(
        that: this,
        samples: samples,
      );

  Stream<Float32List> debugStartRecording() => RustLib.instance.api
      .crateApiClientRustAudioEngineDebugStartRecording(that: this);

  Future<void> disconnect() =>
      RustLib.instance.api.crateApiClientRustAudioEngineDisconnect(that: this);

  Stream<AudioEvent> getEventStream() => RustLib.instance.api
      .crateApiClientRustAudioEngineGetEventStream(that: this);

  Future<void> initializeAudio({
    required String host,
    required int port,
    required List<int> key,
    required List<int> encryptNonce,
    required List<int> decryptNonce,
  }) => RustLib.instance.api.crateApiClientRustAudioEngineInitializeAudio(
    that: this,
    host: host,
    port: port,
    key: key,
    encryptNonce: encryptNonce,
    decryptNonce: decryptNonce,
  );

  Future<void> setAutomaticGainControl({required bool enabled}) =>
      RustLib.instance.api.crateApiClientRustAudioEngineSetAutomaticGainControl(
        that: this,
        enabled: enabled,
      );

  Future<void> setConfig({required MumbleConfig config}) => RustLib.instance.api
      .crateApiClientRustAudioEngineSetConfig(that: this, config: config);

  Future<void> setEchoCancellation({required bool enabled}) =>
      RustLib.instance.api.crateApiClientRustAudioEngineSetEchoCancellation(
        that: this,
        enabled: enabled,
      );

  Future<void> setInputGain({required double gain}) => RustLib.instance.api
      .crateApiClientRustAudioEngineSetInputGain(that: this, gain: gain);

  Future<void> setNoiseSuppression({required bool enabled}) =>
      RustLib.instance.api.crateApiClientRustAudioEngineSetNoiseSuppression(
        that: this,
        enabled: enabled,
      );

  Future<void> setOutputVolume({required double volume}) => RustLib.instance.api
      .crateApiClientRustAudioEngineSetOutputVolume(that: this, volume: volume);

  Future<void> setPtt({required bool active}) => RustLib.instance.api
      .crateApiClientRustAudioEngineSetPtt(that: this, active: active);

  Future<void> setUserVolume({
    required int sessionId,
    required double volume,
  }) => RustLib.instance.api.crateApiClientRustAudioEngineSetUserVolume(
    that: this,
    sessionId: sessionId,
    volume: volume,
  );
}
