// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'hardware/audio.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum TransmissionMode {
  pushToTalk,
  continuous,
  vadThreshold,
  vadAuto,
}

class MumbleConfig {
  final TransmissionMode transmissionMode;

  /// Threshold for VADThreshold mode (0.0 to 1.0)
  final double vadThreshold;

  /// Target bitrate for the Opus encoder in bits per second (e.g. 72000).
  final int outgoingAudioBitrate;

  /// The size of audio chunks sent over the network in milliseconds (e.g. 10ms or 20ms).
  final int outgoingAudioMsPerPacket;

  /// The size of the software jitter buffer in milliseconds.
  /// This intentionally delays playback to handle uneven network packet arrival.
  final int incomingJitterBufferMs;

  /// The ID of the audio output device to use. If None, the default device is used.
  final String? playbackDeviceId;

  /// The requested size of the operating system's hardware playback output buffer.
  final AudioBufferSize playbackHwBufferSize;

  /// The requested size of the operating system's hardware capture input buffer.
  final AudioBufferSize captureHwBufferSize;

  /// The ID of the audio input device to use. If None, the default device is used.
  final String? captureDeviceId;

  /// Enable Acoustic Echo Cancellation (AEC)
  final bool echoCancellation;

  const MumbleConfig({
    this.transmissionMode = TransmissionMode.pushToTalk,
    this.vadThreshold = 0.1,
    required this.outgoingAudioBitrate,
    required this.outgoingAudioMsPerPacket,
    required this.incomingJitterBufferMs,
    this.playbackDeviceId,
    required this.playbackHwBufferSize,
    required this.captureHwBufferSize,
    this.captureDeviceId,
    required this.echoCancellation,
  });

  @override
  int get hashCode =>
      transmissionMode.hashCode ^
      vadThreshold.hashCode ^
      outgoingAudioBitrate.hashCode ^
      outgoingAudioMsPerPacket.hashCode ^
      incomingJitterBufferMs.hashCode ^
      playbackDeviceId.hashCode ^
      playbackHwBufferSize.hashCode ^
      captureHwBufferSize.hashCode ^
      captureDeviceId.hashCode ^
      echoCancellation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleConfig &&
          runtimeType == other.runtimeType &&
          transmissionMode == other.transmissionMode &&
          vadThreshold == other.vadThreshold &&
          outgoingAudioBitrate == other.outgoingAudioBitrate &&
          outgoingAudioMsPerPacket == other.outgoingAudioMsPerPacket &&
          incomingJitterBufferMs == other.incomingJitterBufferMs &&
          playbackDeviceId == other.playbackDeviceId &&
          playbackHwBufferSize == other.playbackHwBufferSize &&
          captureHwBufferSize == other.captureHwBufferSize &&
          captureDeviceId == other.captureDeviceId &&
          echoCancellation == other.echoCancellation;
}
