// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../mumble/config.dart';
import '../mumble/hardware/audio.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'client.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MumbleTextMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<AudioDevice>> listAudioInputDevices() =>
    RustLib.instance.api.crateApiClientListAudioInputDevices();

Future<List<AudioDevice>> listAudioOutputDevices() =>
    RustLib.instance.api.crateApiClientListAudioOutputDevices();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RustAudioEngine>>
abstract class RustAudioEngine implements RustOpaqueInterface {
  Future<void> debugInjectPcm({required List<double> samples});

  Stream<Float32List> debugStartRecording();

  Future<void> disconnect();

  Stream<AudioEvent> getEventStream();

  Future<void> initializeAudio({
    required String host,
    required int port,
    required List<int> key,
    required List<int> encryptNonce,
    required List<int> decryptNonce,
  });

  factory RustAudioEngine() =>
      RustLib.instance.api.crateApiClientRustAudioEngineNew();

  Future<void> setAutomaticGainControl({required bool enabled});

  Future<void> setConfig({required MumbleConfig config});

  Future<void> setEchoCancellation({required bool enabled});

  Future<void> setInputGain({required double gain});

  Future<void> setNoiseSuppression({required bool enabled});

  Future<void> setOutputVolume({required double volume});

  Future<void> setPtt({required bool active});

  Future<void> setUserVolume({required int sessionId, required double volume});
}

@freezed
sealed class AudioEvent with _$AudioEvent {
  const AudioEvent._();

  const factory AudioEvent.audioVolume(double field0) = AudioEvent_AudioVolume;
  const factory AudioEvent.userTalking(int field0, bool field1) =
      AudioEvent_UserTalking;
  const factory AudioEvent.disconnected(String field0) =
      AudioEvent_Disconnected;
}

class MumbleChannel {
  final int id;
  final String name;
  final int? parentId;
  final int position;
  final String? description;
  final bool isEnterRestricted;

  const MumbleChannel({
    required this.id,
    required this.name,
    this.parentId,
    required this.position,
    this.description,
    required this.isEnterRestricted,
  });

  static Future<MumbleChannel> default_() =>
      RustLib.instance.api.crateApiClientMumbleChannelDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      position.hashCode ^
      description.hashCode ^
      isEnterRestricted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleChannel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          position == other.position &&
          description == other.description &&
          isEnterRestricted == other.isEnterRestricted;
}

class MumbleUser {
  final int session;
  final String name;
  final int channelId;
  final bool isTalking;
  final bool isMuted;
  final bool isDeafened;
  final bool isSuppressed;
  final bool isRegistered;
  final int? userId;
  final String? comment;
  final Uint8List? avatar;

  const MumbleUser({
    required this.session,
    required this.name,
    required this.channelId,
    required this.isTalking,
    required this.isMuted,
    required this.isDeafened,
    required this.isSuppressed,
    required this.isRegistered,
    this.userId,
    this.comment,
    this.avatar,
  });

  static Future<MumbleUser> default_() =>
      RustLib.instance.api.crateApiClientMumbleUserDefault();

  @override
  int get hashCode =>
      session.hashCode ^
      name.hashCode ^
      channelId.hashCode ^
      isTalking.hashCode ^
      isMuted.hashCode ^
      isDeafened.hashCode ^
      isSuppressed.hashCode ^
      isRegistered.hashCode ^
      userId.hashCode ^
      comment.hashCode ^
      avatar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MumbleUser &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          name == other.name &&
          channelId == other.channelId &&
          isTalking == other.isTalking &&
          isMuted == other.isMuted &&
          isDeafened == other.isDeafened &&
          isSuppressed == other.isSuppressed &&
          isRegistered == other.isRegistered &&
          userId == other.userId &&
          comment == other.comment &&
          avatar == other.avatar;
}
